name: indexflora-api
version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: docker/Dockerfile.Python.Dev
    restart: unless-stopped
    ports:
      - 8400:8000
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5